config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :designs

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/design.rb
class Design < ApplicationRecord
  belongs_to :user
  has_many :votes

  validates :a, presence: true
  validates :b, presence: true
  validates :title, presence: true

  mount_uploader :a, DesignUploader
  mount_uploader :b, DesignUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :designs

  validates :email, presence: true

  mount_uploader :avatar, AvatarUploader
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :design
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @designs = Design.includes(:user).all
    @votes = Vote.group(:design_id, :a).count
  end

  def show
    @design = Design.find(params[:id])
    @votes = @design.votes.group(:a).count
  end

  def new
    @design = Design.new
  end

  def create
    @design = Design.new(design_params)
    @design.user = current_user

    if @design.save
      redirect_to design_path(@design)
    else
      render :new
    end
  end

  private

  def design_params
    params.require(:design).permit(:a, :b, :title, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user, size=80)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end
end

app/helpers/designs_helper.rb
module DesignsHelper
  def percentage (count, total)
    return 0 if count == 0
    return "#{(count.to_f / total.to_f) * 100}%"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/designs/_design.html.erb
<%
a_votes = @votes[[design.id, true]] || 0
b_votes = @votes[[design.id, false]] || 0
%>
<div class="inline-block">
  <a class="card" href="<%= design_path(design) %>">
    <div class="col-2 col-gap-16">
      <div>
        <img class="placeholder" src="<%= design.a %>" />
      </div>
      <div>
        <img class="placeholder" src="<%= design.b %>" />
      </div>
    </div>
  </a>
  <div class="result">
    <div class="result-header flex">
      <%= image_tag avatar_url(design.user), class: 'result-header-avatar avatar avatar-small', alt: '' %>
      <span class="result-header-name"><%= design.user.name || design.user.email %></span>
      <div class="flex-1"></div>
      <small class="votes"><%= pluralize(a_votes + b_votes, 'vote')%></small>
    </div>
    <%= render 'designs/result_bars', a: a_votes, b: b_votes %>
  </div>
</div>

app/views/designs/_result_bars.html.erb
<div class="result-bars">
  <div class="flex">
    <span class="bar-label color-red">A</span>
    <span class="bar">
      <div class="bar-inner bg-red" style="width: <%= percentage(a, a + b) %>"></div>
    </span>
  </div>
  <div class="flex">
    <span class="bar-label color-blue">B</span>
    <span class="bar">
      <div class="bar-inner bg-blue" style="width: <%= percentage(b, a + b) %>"></div>
    </span>
  </div>
</div>

app/views/designs/index.html.erb
<div class="col-sm-2 col-gap-32">
  <% @designs.each do |design| %>
    <%= render "designs/design", design: design %>
  <% end %>
</div>

app/views/designs/new.html.erb
<div class="form-wrapper">
<h1>Upload designs</h1>

<%= form_for @design, url: designs_path do |form| %>
  <% if @design.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@design.errors.count, "error") %> prohibited this from being saved:
      </h2>
      <ul>
        <% @design.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :a %><br>
    <%= form.file_field :a %>
  </p>

  <p>
    <%= form.label :b %><br>
    <%= form.file_field :b %>
  </p>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit class: 'btn btn-primary' %>
  </p>
<% end %>
</div>

app/views/designs/show.html.erb
<%
a_votes = @votes[true] || 0
b_votes = @votes[false] || 0
%>
<div class="card">
  <div class="col-2 col-gap-16">
    <div>
      <img class="placeholder" src="<%= @design.a %>" />
    </div>
    <div>
      <img class="placeholder" src="<%= @design.b %>" />
    </div>
  </div>
</div>
<div class="result">
  <div class="result-header flex">
    <%= image_tag avatar_url(@design.user), class: 'result-header-avatar avatar avatar-small', alt: '' %>
    <span class="result-header-name"><%= @design.user.name || @design.user.email %></span>
    <div class="flex-1"></div>
    <small class="votes"><%= pluralize(a_votes + b_votes, 'vote')%></small>
  </div>
  <h2><%= @design.title %></h2>
  <p><%= @design.description %></p>
  <%= render 'designs/result_bars', a: a_votes, b: b_votes %>
</div>

app/views/home/index.html.erb
<h1 class="text-center">Aaybee testing, of your dreams. Can I make a change?</h1>
<p class="text-center">
  <a href="/designs/new" class="btn btn-primary">Upload a design</a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aaybee</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="nav nav-top flex">
      <a href="/" class="nav-link logo">aaybee</a>
      <div class="flex-1"></div>
      <% if user_signed_in? %>
        <a href="#" class="nav-link">your tests</a>
        <a href="/designs/new" class="nav-link">upload design</a>
        <a href="<%= destroy_user_session_path %>" class="nav-link" rel="nofollow" data-method="delete">
          <%= image_tag avatar_url(current_user), class: 'avatar avatar-medium', alt: '' %>
        </a>
      <% else %>
        <a href="<%= new_user_session_path %>" class="nav-link">sign in</a>
      <% end %>
    </div>
    <div class="nav flex">
      <a href="/designs" class="nav-link <%= "nav-link-active" if current_page?('/designs') %>">View all</a>
      <a href="#" class="nav-link">View following</a>
      <div class="flex-1"></div>
      <a href="#" class="nav-link">Sort by date</a>
    </div>
    <div class="content">
      <% if notice %>
      <div class="flash flash-notice"><%= notice %></div>
      <% end %>
      <% if alert %>
      <div class="flash flash-alert"><%= alert %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>